<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.550">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Qing Li">

<title>Protein Network from GWAS Hits</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="doc_pheGenoI_network_files/libs/clipboard/clipboard.min.js"></script>
<script src="doc_pheGenoI_network_files/libs/quarto-html/quarto.js"></script>
<script src="doc_pheGenoI_network_files/libs/quarto-html/popper.min.js"></script>
<script src="doc_pheGenoI_network_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="doc_pheGenoI_network_files/libs/quarto-html/anchor.min.js"></script>
<link href="doc_pheGenoI_network_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="doc_pheGenoI_network_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="doc_pheGenoI_network_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="doc_pheGenoI_network_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="doc_pheGenoI_network_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Protein Network from GWAS Hits</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Qing Li </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="goal" class="level2">
<h2 class="anchored" data-anchor-id="goal">Goal</h2>
<p>To use STRING.DB to visualize the network of proteins that is related to hypertension and blood pressure (HTN related traits).</p>
</section>
<section id="source-data" class="level2">
<h2 class="anchored" data-anchor-id="source-data">Source data</h2>
<p>Data original source: https://www.ncbi.nlm.nih.gov/gap/phegeni. The Phenotype-Genotype Integrator (PheGenI), merges NHGRI genome-wide association study (GWAS) catalog data with several databases housed at the National Center for Biotechnology Information (NCBI), including Gene, dbGaP, OMIM, eQTL and dbSNP. More comprehensive lists can be obtained from other sources. For this Codeathon events, we only use this list as a toy example.</p>
<p>Obtain the data from NCBI website</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">#wget "https://www.ncbi.nlm.nih.gov/projects/gap/eqtl/EpiViewBE.cgi?type=dl.tab"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="processing-the-table-of-gwas-results" class="level2">
<h2 class="anchored" data-anchor-id="processing-the-table-of-gwas-results">Processing the table of GWAS results</h2>
<p>In this session, we conducted prelimiary descriptive analysis of the results table. Then we extracted the records related to hypertension and blood pressure (HTN related traits).</p>
<section id="descriptive-analysis-of-gwas-results" class="level3">
<h3 class="anchored" data-anchor-id="descriptive-analysis-of-gwas-results">Descriptive analysis of GWAS results</h3>
<p>For visualization, it is easier to display the significant level of p-value than its original scale.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">"//data/liq4/CCDGS_y2024/codeathon/script_network"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>dd<span class="ot">=</span> <span class="fu">read.csv</span>(<span class="st">"../publicdata/PheGenI_Association_full.tab"</span>, <span class="at">sep=</span><span class="st">"</span><span class="sc">\t</span><span class="st">"</span>, <span class="at">header=</span>T, <span class="at">as.is=</span>T)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(dd)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   136526 obs. of  16 variables:
 $ X.         : int  1 2 3 4 5 6 7 8 9 10 ...
 $ Trait      : chr  "1-Alkyl-2-acetylglycerophosphocholine Esterase" "1-Alkyl-2-acetylglycerophosphocholine Esterase" "1-Alkyl-2-acetylglycerophosphocholine Esterase" "1-Alkyl-2-acetylglycerophosphocholine Esterase" ...
 $ SNP.rs     : int  10782529 7528419 12740374 599839 600550 964184 12286037 10846744 11057841 10144042 ...
 $ Context    : chr  "intergenic" "UTR-3" "UTR-3" "nearGene-3" ...
 $ Gene       : chr  "SSX2IP" "CELSR2" "CELSR2" "PSRC1" ...
 $ Gene.ID    : int  117178 1952 1952 84722 643680 8882 8882 949 949 388011 ...
 $ Gene.2     : chr  "LPAR3" "CELSR2" "CELSR2" "PSRC1" ...
 $ Gene.ID.2  : int  23566 1952 1952 84722 643680 8882 8882 949 949 283598 ...
 $ Chromosome : int  1 1 1 1 11 11 11 12 12 14 ...
 $ Location   : int  84802559 109274569 109274967 109279543 60230192 116778200 116781490 124827878 124832196 98033120 ...
 $ P.Value    : num  4e-06 1e-17 2e-22 3e-15 2e-11 ...
 $ Source     : chr  "NHGRI" "NHGRI" "NHGRI" "NHGRI" ...
 $ PubMed     : int  23118302 22003152 23118302 20442857 23118302 22003152 20442857 20442857 23118302 23118302 ...
 $ Analysis.ID: int  0 0 0 0 0 0 0 0 0 0 ...
 $ Study.ID   : int  NA NA NA NA NA NA NA NA NA NA ...
 $ Study.Name : chr  "" "" "" "" ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="do">## let us modify the pvalue to show -log10() scale</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="do">## need to take care of P.Value=0</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>lowest.P <span class="ot">=</span> <span class="fu">min</span> (dd<span class="sc">$</span>P.Value[dd<span class="sc">$</span>P.Value<span class="sc">!=</span><span class="dv">0</span>])</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>dd<span class="sc">$</span>P.Value[dd<span class="sc">$</span>P.Value<span class="sc">==</span><span class="dv">0</span>] <span class="ot">=</span> lowest.P</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>dd<span class="sc">$</span>p.sig<span class="ot">=</span> <span class="sc">-</span><span class="fu">log10</span>(dd<span class="sc">$</span>P.Value)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Remove outliers from the table. Some traits that comes from one study with many GWAS hits for one trait. For example, to note that “Platelet Function Tests” return 16346 signification SNPs (11% of the GWAS hits). We would consider them as outliers.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'dplyr'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:stats':

    filter, lag</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ forcats   1.0.0     ✔ readr     2.1.5
✔ ggplot2   3.5.0     ✔ stringr   1.5.1
✔ lubridate 1.9.3     ✔ tibble    3.2.1
✔ purrr     1.0.2     ✔ tidyr     1.3.1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>dd<span class="sc">$</span>studyTrait<span class="ot">=</span><span class="fu">paste</span>(dd<span class="sc">$</span>Study.ID, dd<span class="sc">$</span>Trait, <span class="at">sep=</span><span class="st">"_"</span>)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>tb.summary <span class="ot">=</span> dd <span class="sc">%&gt;%</span> <span class="fu">group_by</span> (studyTrait) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">Freq=</span><span class="fu">n</span>()) <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(Freq))</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>tb.summary</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,525 × 2
   studyTrait                                  Freq
   &lt;chr&gt;                                      &lt;int&gt;
 1 375_Platelet Function Tests                15653
 2 267_Child Development Disorders, Pervasive  5121
 3 NA_Bronchodilator Agents                    3459
 4 NA_Lung Volume Measurements                 2296
 5 NA_Body Mass Index                          1992
 6 NA_Forced Expiratory Volume                 1554
 7 NA_Schizophrenia                            1350
 8 342_Echocardiography                        1183
 9 221_Body Height                             1153
10 342_Cholesterol, HDL                        1146
# ℹ 1,515 more rows</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>dd<span class="ot">=</span>dd[<span class="sc">!</span><span class="fu">is.element</span>(dd<span class="sc">$</span>studyTrait, </span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>                  <span class="fu">c</span>(<span class="st">"375_Platelet Function Tests"</span>, <span class="st">"267_Child Development Disorders, Pervasive"</span>)), ]</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(dd)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 115752     18</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>tb.summary <span class="ot">=</span> dd <span class="sc">%&gt;%</span> <span class="fu">group_by</span> (studyTrait) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">Freq=</span><span class="fu">n</span>()) <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(Freq))</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>tb.summary</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1,523 × 2
   studyTrait                   Freq
   &lt;chr&gt;                       &lt;int&gt;
 1 NA_Bronchodilator Agents     3459
 2 NA_Lung Volume Measurements  2296
 3 NA_Body Mass Index           1992
 4 NA_Forced Expiratory Volume  1554
 5 NA_Schizophrenia             1350
 6 342_Echocardiography         1183
 7 221_Body Height              1153
 8 342_Cholesterol, HDL         1146
 9 342_Blood Pressure           1060
10 221_Blood Pressure            971
# ℹ 1,513 more rows</code></pre>
</div>
</div>
<p>Histogram of distribution of counts for SNP, studied traits and nearby genes for significant SNPs. We can see for a majority of the reported GWAS hits, most of the significant SNP are only reported for one trait.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="do">## show the enrichment of trait, SNP and genes</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>tb.trait<span class="ot">=</span><span class="fu">sort</span>(<span class="fu">table</span>(dd<span class="sc">$</span>Trait), <span class="at">decreasing =</span> T)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>tb.SNP <span class="ot">=</span> <span class="fu">sort</span>(<span class="fu">table</span>(dd<span class="sc">$</span>SNP.rs), <span class="at">decreasing =</span> T)</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>tb.gene<span class="ot">=</span><span class="fu">sort</span>(<span class="fu">table</span>(dd<span class="sc">$</span>Gene), <span class="at">decreasing =</span> T)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>tb.psig<span class="ot">=</span><span class="fu">sort</span>(<span class="fu">table</span>(dd<span class="sc">$</span>p.sig), <span class="at">decreasing =</span> T)</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(tb.SNP, <span class="at">main=</span><span class="st">"Histogram of counts of SNPs"</span>) <span class="co">#(1-200, mode=1, there are some 2s)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="doc_pheGenoI_network_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(tb.trait, <span class="at">main=</span><span class="st">"Histogram of counts of traits"</span>) <span class="co">#(1-150000, model=1,2)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="doc_pheGenoI_network_files/figure-html/unnamed-chunk-5-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(tb.gene, <span class="at">main=</span><span class="st">"Histogram of counts of genes annotated for the SNPs"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="doc_pheGenoI_network_files/figure-html/unnamed-chunk-5-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Now let us see the distributions of the p-value significant levels for all GAWS hits</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(tb.psig, <span class="at">main=</span><span class="fu">c</span>(<span class="st">"Histogram of p-value significant levels"</span>, <span class="st">"among all GWAS hits"</span>), <span class="at">xlab=</span><span class="st">"-log10(p-value); the higher value, the more significant"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="doc_pheGenoI_network_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(tb.psig[tb.psig<span class="sc">&lt;=</span><span class="dv">10</span>], <span class="at">xlim=</span><span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">14</span>), <span class="at">main=</span><span class="fu">c</span>(<span class="st">"Histogram of p-value significant levels among all GWAS hits"</span>, <span class="st">"excluding extreme low p.value &lt; 10^(-40)"</span>), <span class="at">xlab=</span><span class="st">"-log10(p-value); the higher value, the more significant"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="doc_pheGenoI_network_files/figure-html/unnamed-chunk-6-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="extract-lists-of-genes-for-htn-related-traits" class="level3">
<h3 class="anchored" data-anchor-id="extract-lists-of-genes-for-htn-related-traits">Extract lists of genes for HTN related traits</h3>
<p>We would like to extract all the GWAS hits for trait “hypertension” and “blood pressure”. For each SNP, the table show the gene annotation. We will use the first two annotated gene as the gene associated with hypertension. If the same gene is associated with other traits, we would also tally the occurrence for those gene implicated for other traits.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>pTrait.filter <span class="ot">=</span> (dd<span class="sc">$</span>Trait<span class="sc">==</span><span class="st">"Hypertension"</span> <span class="sc">|</span> dd<span class="sc">$</span>Trait<span class="sc">==</span><span class="st">"Blood Pressure"</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>dd.trait1<span class="ot">=</span>dd[pTrait.filter, ]</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(dd.trait1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4976   18</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>trait.gene <span class="ot">=</span> <span class="fu">unique</span>(<span class="fu">c</span>(dd.trait1<span class="sc">$</span>Gene, dd.trait1<span class="sc">$</span>Gene<span class="fl">.2</span>))</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(trait.gene)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2907</code></pre>
</div>
</div>
<p>We have 4976 gene implicated for 2907 significant SNPs for HTN related traits. We would like to see the chromosomes distribution of those significant SNPs as well as if those genes are implicated for other significant associations with other traits.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(dd.trait1<span class="sc">$</span>Chromosome)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20 
380 355 331 317 379 302 263 247 199 400 240 285 127 145 271 122 128 101  92 139 
 21  22  23 
 50  44  59 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>dd.otherTrait <span class="ot">=</span> dd[<span class="sc">!</span>pTrait.filter, ]</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(dd.otherTrait)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 110776     18</code></pre>
</div>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>dd.oth1 <span class="ot">=</span> dd.otherTrait[<span class="fu">is.element</span>(dd.otherTrait<span class="sc">$</span>Gene<span class="fl">.1</span>, trait.gene), ]</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>dd.oth2 <span class="ot">=</span> dd.otherTrait[<span class="fu">is.element</span>(dd.otherTrait<span class="sc">$</span>Gene<span class="fl">.2</span>, trait.gene), ]</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>dd.oth <span class="ot">=</span> <span class="fu">rbind</span>(dd.oth1, dd.oth2)</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(<span class="fu">log10</span>(<span class="fu">table</span>(dd.oth<span class="sc">$</span>Trait)))  <span class="do">## on log10 scale for occurance of other traits</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="doc_pheGenoI_network_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>What are the other traits that share the same significant gene association signals as HTN related traits? List the top 20:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>ct.trait <span class="ot">=</span> <span class="fu">table</span>(dd.oth<span class="sc">$</span>Trait)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>tmp <span class="ot">=</span> <span class="fu">sort</span>(ct.trait, <span class="at">decreasing =</span> T)[<span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>]</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>top.relatedT <span class="ot">=</span> <span class="fu">cbind</span>(<span class="at">ct =</span><span class="fu">unlist</span>(tmp))</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>top.relatedT</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                         ct
Body Mass Index                        1135
Bronchodilator Agents                  1134
Cholesterol, HDL                        904
Body Height                             748
Lung Volume Measurements                735
Forced Expiratory Volume                580
Triglycerides                           574
Respiratory Function Tests              567
Cholesterol, LDL                        559
Cholesterol                             473
Schizophrenia                           456
Echocardiography                        452
Body Weight                             408
Electrocardiography                     354
Hip                                     354
Stroke                                  354
Arterial Pressure                       323
Myocardial Infarction                   320
Autistic Disorder                       312
Pulmonary Disease, Chronic Obstructive  274</code></pre>
</div>
</div>
</section>
<section id="identify-other-traits-that-share-the-same-associated-genes" class="level3">
<h3 class="anchored" data-anchor-id="identify-other-traits-that-share-the-same-associated-genes">Identify other traits that share the same associated genes</h3>
<p>Given the list of 4976 genes indicated by HTN related traits, we tally how many the genes also appear for other traits. Take the top three other traits that share the most number of associated genes with HTN related traits.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>oth.totalSNP <span class="ot">=</span> dd.oth <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(Trait) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">Freq=</span><span class="fu">n</span>()) <span class="do">## total SNPs by trait</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>oth.sameGene <span class="ot">=</span> dd.oth <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(Trait) <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">sameG =</span> <span class="fu">is.element</span>(Gene, trait.gene))<span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">sameGCt =</span> <span class="fu">sum</span>(sameG)) <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(sameGCt))</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>oth.sameGene <span class="ot">=</span> oth.sameGene <span class="sc">%&gt;%</span> <span class="fu">merge</span>(oth.totalSNP) <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">prop=</span>sameGCt<span class="sc">/</span>Freq) <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(sameGCt))</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(oth.sameGene<span class="sc">$</span>prop)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="doc_pheGenoI_network_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(oth.sameGene<span class="sc">$</span>sameGCt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="doc_pheGenoI_network_files/figure-html/unnamed-chunk-10-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>oth.sameGene</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                                                                    Trait
1                                                                         Body Mass Index
2                                                                   Bronchodilator Agents
3                                                                        Cholesterol, HDL
4                                                                             Body Height
5                                                                Lung Volume Measurements
6                                                                Forced Expiratory Volume
7                                                              Respiratory Function Tests
8                                                                           Triglycerides
9                                                                        Cholesterol, LDL
10                                                                            Cholesterol
11                                                                          Schizophrenia
12                                                                       Echocardiography
13                                                                            Body Weight
14                                                                    Electrocardiography
15                                                                                    Hip
16                                                                      Arterial Pressure
17                                                                                 Stroke
18                                                                      Autistic Disorder
19                                                                  Myocardial Infarction
20                                                 Pulmonary Disease, Chronic Obstructive
21                                                                    Erythrocyte Indices
22                                                                                Smoking
23                                                                          Heart Failure
24                                                                               Arteries
25                                                                    Waist Circumference
26                                                                      Alzheimer Disease
27                                                                        Waist-Hip Ratio
28                                                                      Erythrocyte Count
29                                                                       Coronary Disease
30                                                             Glomerular Filtration Rate
31                                                                                 Asthma
32                                                                                Glucose
33                                                                       Breast Neoplasms
34                                                              Diabetes Mellitus, Type 2
35                                                                            Personality
36                                                                     C-Reactive Protein
37                                                                                Insulin
38                                                                             Alcoholism
39                                                                       Muscle, Skeletal
40                                                                       Bipolar Disorder
41                                           Insulin-Like Growth Factor Binding Protein 3
42                                                                             Creatinine
43                                                                             Hematocrit
44                                                                                   Iron
45                                                                            Hemoglobins
46                                                                Coronary Artery Disease
47                                                                                 Lipids
48                                                                Platelet Function Tests
49                                                                           Bone Density
50                                                                                Obesity
51                                                                        Immunoglobulins
52                                                                          Blood Vessels
53                                                                      Diabetes Mellitus
54                                                                    Prostatic Neoplasms
55                                          Attention Deficit Disorder with Hyperactivity
56                                                                Cardiovascular Diseases
57                                                                                  Sleep
58                                                                          Blood Glucose
59                                                                      Parkinson Disease
60                                                                              Uric Acid
61                                                                  Body Fat Distribution
62                                                              Body Weights and Measures
63                                                                             Fibrinogen
64                                                                     Lipoproteins, VLDL
65                                                                     Insulin Resistance
66                                                                                  Urine
67                                                                    Depressive Disorder
68                                                          Lupus Erythematosus, Systemic
69                                                             Hemoglobin A, Glycosylated
70                                                                         Lipoprotein(a)
71                                                                              Education
72                                                           Insulin-Like Growth Factor I
73                                                                             Metabolism
74                                                                          Neuroblastoma
75                                                 Cardiovascular Physiological Phenomena
76                                                            Inflammatory Bowel Diseases
77                                                                     Intelligence Tests
78                                                                 Paliperidone Palmitate
79                                                                          Leukoaraiosis
80                                                                    Pulse Wave Analysis
81                                                                Antihypertensive Agents
82                                                                          Crohn Disease
83                                                                              Psoriasis
84                                                                            Thyrotropin
85                                                                           Erythrocytes
86                                                                    Atrial Fibrillation
87                                                                            Eosinophils
88                                                                             Heart Rate
89                                                                     Migraine Disorders
90                                                                           Age of Onset
91                                                                  Arthritis, Rheumatoid
92                                                                                Calcium
93                                                                          Exercise Test
94                                                                              Mortality
95                                                                   Ankle Brachial Index
96                                                            Aspartate Aminotransferases
97                                                                    Colitis, Ulcerative
98                                                                   Macular Degeneration
99                                                                              Neoplasms
100                                                                              Menarche
101                                                              Neuropsychological Tests
102                                                                             Monocytes
103                                                                              Albumins
104                                                                                 HIV-1
105                                                         Amyotrophic Lateral Sclerosis
106                                                                        Platelet Count
107                                                                          Rotator Cuff
108                                            monocyte chemoattractant protein 1 (66-77)
109                                                                      Alcohol Drinking
110                                                             gamma-Glutamyltransferase
111                                                                     Trypanosoma cruzi
112                                                                          Tunica Media
113                                                                  Alanine Transaminase
114                                                                             Bilirubin
115                                                                     Trans Fatty Acids
116                                                                           Hippocampus
117                                                                           Neuroticism
118                                                                      Lymphocyte Count
119                                                                Adenocarcinoma of lung
120                                                                             Longevity
121                                                                            Optic Disk
122                                                                          Testosterone
123                                                                                 Aorta
124                                                                              Emotions
125                                                                           Neutrophils
126                                                 S-(3-hydroxypropyl)cysteine N-acetate
127                                              3-hydroxy-1-methylpropylmercapturic acid
128                                                                            Citalopram
129                                                                    Multiple Sclerosis
130                                                                                 Pulse
131                                                           Gastrointestinal Microbiome
132                                                                             Potassium
133                                                                  Colorectal Neoplasms
134                                                                     Mental Competency
135                                                                   Body Weight Changes
136                                                                        Breast Density
137                                                                 Antineoplastic Agents
138                                                               Carotid Artery Diseases
139                                                                   Cognition Disorders
140                                                                       Leukocyte Count
141                                                                                Sodium
142                                                             Diabetes Mellitus, Type 1
143                                                                  Hypertriglyceridemia
144                                                                           Adiponectin
145                                                                       Atrial Pressure
146                                                                Diabetic Nephropathies
147                                                      Receptors, Tumor Necrosis Factor
148                                                              Toluene 2,4-Diisocyanate
149                                                                  Pancreatic Neoplasms
150                                                                 Cognitive Dysfunction
151                                                                         Hemoglobin A2
152                                                         Hypertrophy, Left Ventricular
153                                                                       lipoprotein A-I
154                                                                         Interleukin-6
155                                                                Venous Thromboembolism
156                                                                      Fetal Hemoglobin
157                                                                        Adipose Tissue
158                                                                         Anthropometry
159                                                                  Metabolic Syndrome X
160                                                                       Drug Resistance
161                                                                        Language Tests
162                                                                      Mental Disorders
163                                                                             Basophils
164                                                                   Blood Urea Nitrogen
165                                                                                 Brain
166                                                                        Vital Capacity
167                                                      Age-Related Hearing Impairment 1
168                                                               Cell Adhesion Molecules
169                                                                 Personality Inventory
170                                                                       Vaccine Potency
171                                                            Gastrointestinal Neoplasms
172                                                                              Selenium
173                                                                 Antidepressive Agents
174                                                                      gamma-Tocopherol
175                                                                      alpha-Tocopherol
176                                                       Amyotrophic lateral sclerosis 1
177                                                                   Hydrochlorothiazide
178                                                                        Hydrocortisone
179                                                Leukemia, Lymphocytic, Chronic, B-Cell
180                                                                       Social Behavior
181                                                                  Alkaline Phosphatase
182                                        Precursor Cell Lymphoblastic Leukemia-Lymphoma
183                                                                           Albuminuria
184                                                             Blood Coagulation Factors
185                                                                        Cryptorchidism
186                                                                             Estradiol
187                                                          Renal Insufficiency, Chronic
188                                                                              Altruism
189                                                        Carcinoma, Non-Small-Cell Lung
190                                                                      Subcutaneous Fat
191                                                                  Arthritis, Psoriatic
192                                                                       Atherosclerosis
193                                                                          Homocysteine
194                                                                      Job Satisfaction
195                                                                                Memory
196                                                                         Periodontitis
197                                                                       Alpha-Globulins
198                                                                      Conduct Disorder
199                                                                Dehydroepiandrosterone
200                                                                                  Gout
201                                                                                Leptin
202                                                    Nutritional and Metabolic Diseases
203                                                                  Platelet Aggregation
204                                                          Sex Hormone-Binding Globulin
205                                                                   Cerebrospinal Fluid
206                                                                      dimethylarginine
207                                                      oxidized low density lipoprotein
208                                                           Substance-Related Disorders
209                                                            Surveys and Questionnaires
210                                                                           Transferrin
211                                                           Tumor Necrosis Factor-alpha
212                                                                Vascular Calcification
213                                                                               Anxiety
214                                                                           candesartan
215                                                                         Dental Caries
216                                                                                  Diet
217                                                             Extraversion (Psychology)
218                                                                              Resistin
219                                                                      Circadian Rhythm
220                                                                     Dextroamphetamine
221                                                             Electromagnetic Radiation
222                                                                          Cardiomegaly
223                                                                             Cytokines
224                                                       Influenza A Virus, H1N1 Subtype
225                                                                          Lipoproteins
226                                                                             Menopause
227                                                               Plaque, Atherosclerotic
228                                                                                  Rest
229                                                                          Vitamin B 12
230                                                                 25-Hydroxyvitamin D 2
231                                                                            Aggression
232                                                                       Behcet Syndrome
233                                                                               Leprosy
234                                                                             Magnesium
235                                                       Maximal Midexpiratory Flow Rate
236                                                                          Osteoporosis
237                                                             Prostate-Specific Antigen
238                                                              Receptors, Interleukin-6
239                                                                          White Matter
240                                                                              Alopecia
241                                                                     Apolipoproteins B
242                                                Child Development Disorders, Pervasive
243                                                                    Dermatitis, Atopic
244                                                                  Intraocular Pressure
245                                                                     Ovarian Neoplasms
246                                                      Stress Disorders, Post-Traumatic
247                                                                              Survival
248                                                                  alpha-Linolenic Acid
249                                                                               Anatomy
250                                                                   Blood Sedimentation
251                                                                      Multiple Myeloma
252                                                                  Myopia, Degenerative
253                                                         Obsessive-Compulsive Disorder
254                                                                         Phospholipids
255                                                                 Social Responsibility
256                      Autosomal dominant compelling helio ophthalmic outburst syndrome
257                                                                        Beta-Globulins
258                                                                      Body Composition
259                                                                             Cleft Lip
260                                                                            E-Selectin
261                                                                         Energy Intake
262                                                                              Epilepsy
263                                                                             Ferritins
264                                                                            Folic Acid
265                                                                            Loneliness
266                                                                Receptors, Transferrin
267                                                                  Tobacco Use Disorder
268                                                                        Varicose Veins
269                                                             Atrial Natriuretic Factor
270                                                                        Celiac Disease
271                                                                          Cleft Palate
272                                                                                Coffee
273                                                  Hydroxymethylglutaryl CoA Reductases
274                                                                   Intra-Abdominal Fat
275                                                              Liver Cirrhosis, Biliary
276                                                                            Paclitaxel
277                                                    Peripheral Nervous System Diseases
278                                                             Polychlorinated Biphenyls
279                                                                            Urinalysis
280                                                                             Vitamin A
281                                                                           Vitamin B 6
282                                                                     Apolipoproteins C
283                                                                   Arthritis, Juvenile
284                                                                           Blood Cells
285                                                                   Blood Flow Velocity
286                                                                             Cognition
287                                                                        Interleukin-18
288                                                                            Live Birth
289                                                                                Lutein
290                                                                        Mood Disorders
291                                                           Serotonin Uptake Inhibitors
292                                                                Sulfonylurea Compounds
293                                                                      Taste Perception
294                                                                           Zeaxanthins
295                                                                         Abdominal Fat
296                                                                           Bevacizumab
297                                                                 Cardiovascular System
298                                                                           CD40 Ligand
299                                                                             Cystatins
300                                                                           Fenofibrate
301                                                                       Gestational Age
302                                                                     Homovanillic Acid
303                                                                      Hypersensitivity
304                                                                        Interleukin-12
305                                                                         Interleukin-8
306                                                                Lactate Dehydrogenases
307                                                      Macrophage Inflammatory Proteins
308                                                                                Myopia
309                                                                             Vitamin D
310                                                                          Acceleration
311                                                                  Antipsychotic Agents
312                                                                         beta Carotene
313                                                                                Breast
314                                                Chemical and Drug Induced Liver Injury
315                                                                             Clozapine
316                                                                            Depression
317                                                                             Emphysema
318                                                                           Fatty Acids
319                                                                             Fertility
320                                                                        Heart Diseases
321                                                                      Interferon-gamma
322                                                                        Interleukin-10
323                                                                              lycopene
324                                                                        Motor Activity
325                                                     Plasminogen Activator Inhibitor 1
326                                                                        Social Support
327                                                                        Virus Diseases
328                                                                              Warfarin
329                                                                   Anemia, Sickle Cell
330                                                                    Apolipoprotein A-I
331                                                                 Audiometry, Pure-Tone
332                                                                        Blood Proteins
333                                                                 Carcinoma, Basal Cell
334                                                                         Cell Survival
335                                                                       Creatine Kinase
336                                                                     Crown-Rump Length
337                                                                        Cryptoxanthins
338                                                            Depressive Disorder, Major
339                                                                              Eyebrows
340                                                          Follicle Stimulating Hormone
341                                                        Glucosephosphate Dehydrogenase
342                                                                            Hair Color
343                                                              Hydroxyindoleacetic Acid
344                                                                       Life Expectancy
345                                                                               Lithium
346                                                                           Lymphocytes
347                                                                  Pancreatic Carcinoma
348                                                                            Phosphorus
349                                                                              Proteins
350                                                                         Survival Rate
351                                                       Transforming Growth Factor beta
352                                                                          Tuberculosis
353                                                                     Vascular Diseases
354                                                               Adrenal Cortex Hormones
355                                                                  alpha-Macroglobulins
356                                              Angiotensin-Converting Enzyme Inhibitors
357                                                                       Blood Viscosity
358                                                                      Carotid Arteries
359                                                                                  Chin
360                                                        Drug Hypersensitivity Syndrome
361                                                                         Eye Movements
362                                                        gamma-Glutamylcyclotransferase
363                                                                          Intelligence
364                                                     Intercellular Adhesion Molecule-1
365                                                            Methoxyhydroxyphenylglycol
366                                                                       Motion Sickness
367                                                                                  Nose
368                                                                   Parathyroid Hormone
369                                                           Subcutaneous Fat, Abdominal
370                                                                          tau Proteins
371                                                                Tumor Necrosis Factors
372                                        1-Alkyl-2-acetylglycerophosphocholine Esterase
373                                                                    Airway Obstruction
374                                                                           Amino Acids
375                                                                           Astigmatism
376                                                                       Auditory Cortex
377                                                                 Binge-Eating Disorder
378                                                            Bronchopulmonary Dysplasia
379                                                                              Chlorine
380                                                                             Cisplatin
381                                                                Death, Sudden, Cardiac
382                                                                             efavirenz
383                                                                             Esthetics
384                                                                            Factor VII
385                                                                               Ghrelin
386                                                                  Glycerophospholipids
387                                                                        Hypothyroidism
388                                                                        Lung Neoplasms
389                                                                              Melanoma
390                                                                            P-Selectin
391                                                                       Plaque, Amyloid
392                                                                    Potassium, Dietary
393                                                                     Refractive Errors
394                                                                        alpha-carotene
395                                                                                 Anger
396                                                                           Angiography
397                                                                   Autoimmune Diseases
398                                                                     Barrett Esophagus
399                                                                              Cannabis
400                                                               Cytokine Receptor gp130
401                                                                  Diabetic Retinopathy
402                                                                 Docosahexaenoic Acids
403                                          Insulin-Like Growth Factor Binding Protein 1
404                                                                     Interleukin-1beta
405                                                                       Liver Cirrhosis
406                                                                       Marijuana Abuse
407                                                     Non-alcoholic Fatty Liver Disease
408                                                                   Psychotic Disorders
409                                                                    Refraction, Ocular
410                                                      Reverse Transcriptase Inhibitors
411                                                                    Rhinitis, Allergic
412                                                          Tissue Plasminogen Activator
413                                                                 von Willebrand Factor
414                                                                               Walking
415                                                           amyloid beta-protein (1-42)
416                                                          Antibodies, Antiphospholipid
417                                                                              Behavior
418                                                                     Bladder Exstrophy
419                                                                      Carotid Stenosis
420                                                               Communication Disorders
421                                                                            Compliance
422                                                               Diet, Sodium-Restricted
423                                                                               Fantasy
424                                                                          Fluorescence
425                                                        Fructose-Bisphosphate Aldolase
426                                                                                  Gait
427                                                                       gamma-Globulins
428                                                                  gamma-Linolenic Acid
429                                                                         Hand Strength
430                                                                              Hormones
431                                             Interleukin 1 Receptor Antagonist Protein
432                                                                            Leukocytes
433                                                            Natriuretic Peptide, Brain
434                                                                          Nitric Oxide
435                                                                     Seizures, Febrile
436                                                                         Temporal Lobe
437                                                                              Vitiligo
438                                                              Wet Macular Degeneration
439                                                          13,16,19-docosatrienoic acid
440                                                                              abacavir
441                                                                       Agranulocytosis
442                                                                     Apolipoproteins E
443                                                                       Bulimia Nervosa
444                                                      Deafness, Aminoglycoside-Induced
445                                                                    Educational Status
446                                                                  Fatty Acids, Omega-6
447                                                                       Glucocorticoids
448                                                                                  Hair
449                                                                           Hypospadias
450                                                                 IL1RL1 protein, human
451                                                                  Mean Platelet Volume
452                                                                      Mental Processes
453                                                     Mucocutaneous Lymph Node Syndrome
454                                                                             Myoglobin
455                                                                         Osteonecrosis
456                                                                            Overweight
457                                                                 Pelvic Organ Prolapse
458                                                                   Pulmonary Emphysema
459                                                                 Reproductive Behavior
460                                                                    Sjogren's Syndrome
461                                                               Spondylitis, Ankylosing
462                                                                      Thyroid Diseases
463                                                                             Thyroxine
464                                                                      Triiodothyronine
465                                                                             Vitamin K
466                                                                     Anxiety Disorders
467                                                                           Brain Waves
468                                                                             Clusterin
469                                                                    DNA, Mitochondrial
470                                                                             docetaxel
471                                                                 docosapentaenoic acid
472                                                                        Erythropoietin
473                                                                             Exanthema
474                                                                           gemcitabine
475                                                                                   HIV
476                                                           Intervertebral disc disease
477                                                                 Intracranial Aneurysm
478                                                                           lamotrigine
479                                                                         Linoleic Acid
480                                                                       Lupus Nephritis
481                                                                   Luteinizing Hormone
482                                                                         Mental Health
483                                                                             Methadone
484                                                              Opioid-Related Disorders
485                                                                               Reading
486                                                                           Risperidone
487                                                                         Tonsillectomy
488                                                                     Tourette Syndrome
489                                                                           Transplants
490                                                                              zileuton
491                                                                                 Aging
492                                                                             Attention
493                                                                         Brain Mapping
494                                                           Bronchial Provocation Tests
495                                                                              Caffeine
496                                                              Calcium-Binding Proteins
497                                                                           Carboplatin
498                                                               Carcinoma, Endometrioid
499                                                                Cerebrovascular Trauma
500                                                                       Choice Behavior
501                                                                   Cold-Shock Response
502                                                                    Corneal Topography
503                                                                      Cyclophosphamide
504                                                                       DNA Methylation
505                                                                 Endometrial Neoplasms
506                                                                         Endometriosis
507                                                                     Energy Metabolism
508                                                                  Erectile Dysfunction
509                                                                  Esophageal Neoplasms
510                                                                               Leucine
511                                                                           Lewy Bodies
512                                                               Multiple System Atrophy
513                                                               Neurofibrillary Tangles
514                                                                        Occipital Lobe
515                                                        Ocular Physiological Phenomena
516                                                                     Orofacial Cleft 1
517                                             Receptors, Tumor Necrosis Factor, Type II
518                                                                    Respiratory System
519                                                          Rhinitis, Allergic, Seasonal
520                                           Skin-Hair-Eye Pigmentation, Variation In, 9
521                                                              Sleep Apnea, Obstructive
522                                                                         Acne Vulgaris
523                                                           Adenocarcinoma Of Esophagus
524                                                        Affective Disorders, Psychotic
525                                                                 Amyloid beta-Peptides
526                                 Amyloidosis, Cerebral, with Spongiform Encephalopathy
527                                                                      Anorexia Nervosa
528                                                                         Assertiveness
529                                                                             Bupropion
530                                                              Calcium Channel Blockers
531                                                              Carcinoma, Squamous Cell
532                                                                          coenzyme Q10
533                                                                            Conscience
534                                                                     Coronary Aneurysm
535                                                                              Cotinine
536                                                                                 Cough
537                                                                              Dementia
538                                                 Diagnostic Techniques, Cardiovascular
539                                                                             Dizziness
540                                                                 Eicosapentaenoic Acid
541                                                               Glaucoma, Angle-Closure
542                                                                    GRN protein, human
543                                                                       Hodgkin Disease
544                                                               Insulin-Secreting Cells
545                                                                       Kidney Diseases
546                                                              Linoleoyl-CoA Desaturase
547                                                                            Microbiota
548                                                            Neurodegenerative Diseases
549                                                                  Osteoarthritis, Knee
550                                                                                Otitis
551                                                                          Pancreatitis
552                                                                            Peroxidase
553                                                                        Prion Diseases
554                                                                           Proteinuria
555                                                                               Puberty
556                                                                 Respiration Disorders
557                                                                 Scleroderma, Systemic
558                                                                         Serum Albumin
559                                                                        Skin Neoplasms
560                                                                         Sphingolipids
561                                                                 Staphylococcus aureus
562                                                                           Temperament
563                                                                  Testicular Neoplasms
564                                                                              Thinness
565                                                                         Thyroid Gland
566                                                                   Acute Kidney Injury
567                                                                         acylcarnitine
568                            Anti-Neutrophil Cytoplasmic Antibody-Associated Vasculitis
569                                                                            Antibodies
570                                                                       Anticonvulsants
571                                                                        Autoantibodies
572                                                                     Axial Length, Eye
573                                                                            Biomarkers
574                                                                          Birth Weight
575                                                                     Blood Circulation
576                                                                   Bronchitis, Chronic
577                                                                             Buspirone
578                                                                               Cadmium
579                                                                        Chemokine CCL2
580                                                               Cholangitis, Sclerosing
581                                                      Common Variable Immunodeficiency
582                                                            Diagnostic Self Evaluation
583                                                            Digestive System Neoplasms
584                                                                 Disease-Free Survival
585                                                              Eosinophilic Esophagitis
586                                                                      Essential Tremor
587                                                                                  Face
588                                                                          Frontal Lobe
589                                                                 Functional Laterality
590                                                                  Glaucoma, Open-Angle
591                                                               Glomerulonephritis, IGA
592                                                                         Glycoproteins
593                                                                        Graves Disease
594                                                         hemoglobin A1c protein, human
595  Hypertension, Early-Onset, Autosomal Dominant, with Severe Exacerbation in Pregnancy
596                                                                      Immunoglobulin E
597                                                                     Joint Instability
598                                                           Lung Diseases, Interstitial
599                                                              Mycobacterium Infections
600                                                                        Osteoarthritis
601                                                                           Parasitemia
602                                                                          Perphenazine
603                                                                      Rectal Neoplasms
604                                                                Restless Legs Syndrome
605                                                    Sexual Dysfunctions, Psychological
606                                                   Tomography Scanners, X-Ray Computed
607                                                              Topoisomerase Inhibitors
608                                               Anti-Inflammatory Agents, Non-Steroidal
609                                                                        Anticoagulants
610                                                                          Antioxidants
611                                                                      Arachidonic Acid
612                                                                            Bortezomib
613                                                                       Cerebral Cortex
614                                                                 Chagas Cardiomyopathy
615                                                                    Corneal Pachymetry
616                                                                       Corpus Striatum
617                                                                            Cytarabine
618                                                                 Dupuytren Contracture
619                                                                         Ear, External
620                                                                                Eating
621                                                                              Embolism
622                                                                   Epilepsies, Partial
623                                                               Epilepsy, Temporal Lobe
624                                                                            Everolimus
625                                                                Family Characteristics
626                                                                 Gallbladder Neoplasms
627                                                                Galvanic Skin Response
628                                                                              Glaucoma
629                                                                                Growth
630                                                                  Heart Function Tests
631                                                                  Hepatitis B, Chronic
632                                                                           Hepatitis C
633                                                                             Hepcidins
634                                                                      Immunoglobulin G
635                                                                             Lactation
636                                                                     Lewy Body Disease
637                                                                                 Logic
638                                                                          Methotrexate
639                                                                   Mouth Abnormalities
640                                                              Nasopharyngeal Neoplasms
641                                                               Oropharyngeal Neoplasms
642                                                                       Ovarian Reserve
643                                                                Recombination, Genetic
644                                                                             Scoliosis
645                                                                   Sensation Disorders
646                                                                         Severe Dengue
647                                            Sleep Initiation and Maintenance Disorders
648                                                                               Suicide
649                                                                    Suicide, Attempted
650                                                                   Tetralogy of Fallot
651                                                         thyroid microsomal antibodies
652                                                                            Troponin T
653                                                           amyloid beta-protein (1-40)
654                                                                       Antimetabolites
655                                                            Aortic Aneurysm, Abdominal
656                                                                               Arsenic
657                                                                  beta 2-Microglobulin
658                                                                                 blood
659                                                                             C-Peptide
660                                                                             Cartilage
661                                                         Cataract, Age-Related Nuclear
662                                                                     Cognitive Therapy
663                                                           Conotruncal cardiac defects
664                                                                Coronary Artery Bypass
665                                                                                  Dust
666                                                                  Egg Hypersensitivity
667                                                                              Exercise
668                                                                            Exhalation
669                                                                               Fingers
670                                                                      Fluoroquinolones
671                                                                          Fluorouracil
672                                                               Gastroesophageal Reflux
673                                                                                Glioma
674                                                                             Hepatitis
675                                                                        HIV Infections
676                                                              Hypotension, Orthostatic
677                                                                           iloperidone
678                                                      Influenza A Virus, H10N8 Subtype
679                                                                            irinotecan
680                                                                    Language Disorders
681                                                                  Lymphoma, Follicular
682                                                       Lymphoma, Large B-Cell, Diffuse
683                                                            Microsatellite Instability
684                                                                 Migraine without Aura
685                                                                     Myasthenia Gravis
686                                                                            Narcolepsy
687                                                                          Neuroimaging
688                                                                    Neurotic Disorders
689                                                                                 Nevus
690                                                                            olanzapine
691                                                                        Panic Disorder
692                                                           Partial Thromboplastin Time
693                                                           Peripheral Arterial Disease
694                                                                     Prefrontal Cortex
695                                                                       Premature Birth
696                                                                             Protein C
697                                                      Psychiatric Status Rating Scales
698                                                                    Psychotropic Drugs
699                                                                              Saccades
700                                                           Seasonal Affective Disorder
701                                                             Severity of Illness Index
702                                                                  Sleep Wake Disorders
703                                                              Stevens-Johnson Syndrome
704                                                                     Stomach Neoplasms
705                                                                 Stress, Psychological
706                                                                          Theta Rhythm
707                                                                            Thioamides
708                                                                      Thyroid Hormones
709                                                             Urinary Bladder Neoplasms
710                                                            Uterine Cervical Neoplasms
711                                                                           Vincristine
712                                                                              Vitamins
713                                                    Acquired Immunodeficiency Syndrome
714                                                                             Allergens
715                                                                   alpha 1-Antitrypsin
716                                                                          Alpha Rhythm
717                                                                                Anemia
718                                                                            Angioedema
719                                                             Aortic Aneurysm, Thoracic
720                                                                          Asparaginase
721                                                                     Asperger Syndrome
722                                                                               Aspirin
723                                                                 Atrial Function, Left
724                                                                              Blinking
725                                                                        Breast Feeding
726                                                                 Butyrylcholinesterase
727                                                                 Calorimetry, Indirect
728                                                              Carcinoembryonic Antigen
729                                                    Carotid Intimal Medial Thickness 1
730                                                                              Cataract
731                                                                Central Nervous System
732                                                               chemerin protein, human
733                                                                       Chemokine CCL11
734                                                                        Chemokine CCL5
735                                                                Chemotherapy, Adjuvant
736                                                                        Child Behavior
737                                                             Cholinesterase Inhibitors
738                                                                     Colonic Neoplasms
739                                                                         Complement C4
740                                                              Constriction, Pathologic
741                                                                                Copper
742                                                                      Craniosynostoses
743                                                                            Cystatin C
744                                                                          Delta Rhythm
745                                                                            Diclofenac
746                                                                          Dietary Fats
747                                                     Disorders of Excessive Somnolence
748                                                                           Doxorubicin
749                                                                     Drinking Behavior
750                                                                              Dyslexia
751                                                                            Employment
752                                                                 Epilepsy, Generalized
753                                                   Epstein-Barr Virus Nuclear Antigens
754                                                                  Exfoliation Syndrome
755                                                                             Eye Color
756                                                                   Femur Head Necrosis
757                                                                 fibrinogen D fragment
758                                                                  Gallbladder Diseases
759                                                                              Gambling
760                                                                              Genotype
761                                                        Glomerulonephritis, Membranous
762                                                                Glucose Tolerance Test
763                                                  Glycosylation End Products, Advanced
764                                                               Head and Neck Neoplasms
765                                                                     Hematologic Tests
766                                                                     Heroin Dependence
767                                                                         Hip Fractures
768                                                                     homoharringtonine
769                                                                             Hyperopia
770                                                                      Immunoglobulin A
771                                           Insulin-Like Growth Factor Binding Proteins
772                                                                      Interferon-alpha
773                                                                Kidney Transplantation
774                                                                              Language
775                                                                    Lateral Ventricles
776                                                                            Leukopenia
777                                                                     Lipoproteins, LDL
778                                                       Lymphoma, B-Cell, Marginal Zone
779                                                                               Malaria
780                                                                  Medication Adherence
781                                                                    Memory, Short-Term
782                                                                             Metformin
783                                                                 Mitral Valve Prolapse
784                                                                               Muscles
785                                                                         Odontogenesis
786                      Ossification of the posterior longitudinal ligament of the spine
787                                                                    Osteitis Deformans
788                                                                       Osteoprotegerin
789                                                                          Osteosarcoma
790                                                                          Otitis Media
791                                                                                  Pain
792                                                                             Paralysis
793                                                                         Parietal Lobe
794                                                                  PCSK9 protein, human
795                                                                         Pre-Eclampsia
796                                                                             Protein S
797                                                                  Pyoderma Gangrenosum
798                                                                      Retinal Diseases
799                                                                                Sepsis
800                                          Serotonin Plasma Membrane Transport Proteins
801                                                                            Sertraline
802                                                                           Simvastatin
803                                                                     Skin Pigmentation
804                                                                                 Smell
805                                                                              Sneezing
806                                                                                Suntan
807                                                                            tamsulosin
808                                                                            Thrombosis
809                                                                     Thyroid Neoplasms
810                                                                                 Tooth
811                                                                        Tooth Eruption
812                                                                            triptolide
813                                                                             Urticaria
814                                                                               Viruses
815                                                                         Wernicke Area
816                                                                                  Wine
817                                                                                  Zinc
818                                                                           ziprasidone
819                                                                     Alagille Syndrome
820                                                                       Alopecia Areata
821                                                                              Amygdala
822                                                                             Androgens
823                                                                        Anthracyclines
824                                                                 Anti-Bacterial Agents
825                                                      Antidepressive Agents, Tricyclic
826                                                                              Antigens
827                                                     antithrombin III-protease complex
828                                                                  Arrhythmias, Cardiac
829                                                        Atrioventricular Septal Defect
830                                                              Autism Spectrum Disorder
831                                                                           Azoospermia
832                                                                            Bacteremia
833                                                                      Basal Metabolism
834                                    beta-amyloid peptide 1-42 (E22delta) click peptide
835                                                                       Biliary Atresia
836                                                                            Birth Rate
837                                                                             Bleomycin
838                                                                       Blood Platelets
839                                                                                Braces
840                                                                          Camptothecin
841                                                                    Carcinoma, Lobular
842                                             Carcinoma, squamous cell of head and neck
843                                                                       Caudate Nucleus
844                                                           Cerebral Amyloid Angiopathy
845                                                                        Chemokine CCL4
846                                                                Cicatrix, Hypertrophic
847                                                        Clinical Laboratory Techniques
848                                                                              Clubfoot
849                                                                      Cluster Headache
850                                                                  Contrast Sensitivity
851                                                          cyclic citrullinated peptide
852                                                                       Cytomegalovirus
853                                                            Cytomegalovirus Infections
854                                                                                 Death
855                                                                 Deglutition Disorders
856                                                         delta-5 fatty acid desaturase
857                                                                       Dermatomyositis
858                                                                 Diabetes, Gestational
859                                                                        Diet, High-Fat
860                                                             Digestive System Diseases
861                                                                            DNA Damage
862                                                                         Down Syndrome
863                                                                              Dystonia
864                                                    Esophageal Squamous Cell Carcinoma
865                                                                           Factor VIII
866                                                                            Femur Neck
867                                                                 Food Hypersensitivity
868                                                                       Fractures, Bone
869                                                               Frontotemporal Dementia
870                                                                            Gallstones
871                                                                             Gastritis
872                                                                       Gaucher Disease
873                                                                  Giant Cell Arteritis
874                                                      Granulomatosis with Polyangiitis
875                                                                 Graves Ophthalmopathy
876                                                                     Hashimoto Disease
877                                                                                Health
878                                                                               Hearing
879                                                                          Hearing Loss
880                                                             Heart Defects, Congenital
881                                                               Helicobacter Infections
882                                                                  Hepatitis C, Chronic
883                                                                 Hepatitis, Autoimmune
884                                                                      Hernia, Inguinal
885                                                                  Herpesvirus 1, Human
886                                                                  Herpesvirus 8, Human
887                                                                  Hirschsprung Disease
888                                                           Hormone Replacement Therapy
889                                                               Hypertension, Pulmonary
890                                                         Idiopathic Pulmonary Fibrosis
891                                                                     Infertility, Male
892                                                                       Interferon-beta
893                                                                 Iron-Binding Proteins
894                                                                           Keratoconus
895                                                               L-Lactate Dehydrogenase
896                                                           Lacrimal Apparatus Diseases
897                                                                             Leiomyoma
898                                                                                   Lip
899                                                            Liver Cirrhosis, Alcoholic
900                                                                        Liver Diseases
901                                                                                Lysine
902                                                                               Mannose
903                                                                           Mathematics
904                                                             Matrix Metalloproteinases
905                                                          Medicine, Korean Traditional
906                                                                             Melanosis
907                                                                            Metabolome
908                                                                       Methylphenidate
909                                    Monoclonal Gammopathy of Undetermined Significance
910                                                                           montelukast
911                                                                       Mouth Neoplasms
912                                                                                 Mucus
913                                                                              Myositis
914                                                                      Neoplasm Grading
915                                                                             Neuralgia
916                                                                     Oligoclonal Bands
917                                                             Osteochondritis Dissecans
918                                                                          Otosclerosis
919                                                                              Oximetry
920                                                                          Pelvic Bones
921                                                                            Pesticides
922                                                                         Phenylalanine
923                                                               Pneumococcal Infections
924                                                                        Pneumoconiosis
925                                                                             Pneumonia
926                                                             Polycystic Ovary Syndrome
927                                      Precursor B-Cell Lymphoblastic Leukemia-Lymphoma
928                                                                   Primary amyloidosis
929                                                         Primary Ovarian Insufficiency
930                                                  pro-brain natriuretic peptide (1-76)
931                                                                             Prognosis
932                                                                   Protease Inhibitors
933                                                                           Prothrombin
934                                                               Psychomotor Performance
935                                                          Psychoses, Substance-Induced
936                                                                    Pulmonary Embolism
937                                             Pulmonary Surfactant-Associated Protein D
938                                                                               Purines
939                                                                               Putamen
940                                                        Pyloric Stenosis, Hypertrophic
941                                                                   Quetiapine Fumarate
942                                                                                 Renin
943                                                                        Rhabdomyolysis
944                                 Rhegmatogenous Retinal Detachment, Autosomal Dominant
945                                                                     Rheumatoid Factor
946                                                                              Rifampin
947                                                                 Rotator Cuff Injuries
948                                                                       Salivary Glands
949                                                                            sam so eum
950                                                                           Sarcoidosis
951                                                                       Serologic Tests
952                                                                             Serotonin
953                                                                   Sex Characteristics
954                                                                         Shock, Septic
955                                                                     Silicon Compounds
956                                                                     Speech Perception
957                                                                     Suicidal Ideation
958                                                                              Sulfates
959                                                                               Sunburn
960                                                              Takotsubo Cardiomyopathy
961                                                                              Telomere
962                                                                          temozolomide
963                                                     Temporomandibular Joint Disorders
964                                                          thiopurine methyltransferase
965                                                                        Thrombomodulin
966                                                                           Tocopherols
967                                                                Tooth Demineralization
968                                                                              toxicity
969                                                      Triple Negative Breast Neoplasms
970                                                                              Tyrosine
971                                                                  Urinary Incontinence
972                                                   Vascular Endothelial Growth Factors
973                                                                     Vascular Grafting
974                                                             Venlafaxine Hydrochloride
975                                                            Ventricular Function, Left
976                                                                      Vision Disorders
977                                                                  Vitamin D Deficiency
978                                                             Vitamin D-Binding Protein
979                                                                             Vitamin E
980                                                                                 Voice
981                                                                           Wilms Tumor
982                                                              Aggressive Periodontitis
983                                                                           Beta Rhythm
984                                                                        Bone and Bones
985                                                                 Carcinoma, Renal Cell
986                                                                         CD4-CD8 Ratio
987                                                            Creutzfeldt-Jakob Syndrome
988                                                                       Cystic Fibrosis
989                                                                        Gastric Bypass
990                                                                                  Head
991                                                                          Inflammation
992                                                                         Lung Diseases
993                                                        Lupus Erythematosus, Cutaneous
994                                                                 Milk Hypersensitivity
995                                                          Myeloproliferative Disorders
996                                                 Neonatal Systemic lupus erythematosus
997                                                                           Peroxidases
998                                                                      Problem Behavior
999                                                                     Smoking Cessation
1000                                                                           Uromodulin
1001                                                                          Uteroglobin
     sameGCt Freq      prop
1       1061 1135 0.9348018
2       1048 1134 0.9241623
3        801  904 0.8860619
4        671  748 0.8970588
5        670  735 0.9115646
6        541  580 0.9327586
7        533  567 0.9400353
8        498  574 0.8675958
9        492  559 0.8801431
10       432  473 0.9133192
11       407  456 0.8925439
12       399  452 0.8827434
13       369  408 0.9044118
14       335  354 0.9463277
15       329  354 0.9293785
16       316  323 0.9783282
17       314  354 0.8870056
18       292  312 0.9358974
19       283  320 0.8843750
20       247  274 0.9014599
21       228  266 0.8571429
22       227  250 0.9080000
23       224  260 0.8615385
24       211  243 0.8683128
25       206  242 0.8512397
26       198  227 0.8722467
27       197  220 0.8954545
28       195  223 0.8744395
29       186  192 0.9687500
30       185  202 0.9158416
31       184  217 0.8479263
32       181  208 0.8701923
33       173  191 0.9057592
34       172  184 0.9347826
35       172  211 0.8151659
36       171  192 0.8906250
37       168  192 0.8750000
38       165  191 0.8638743
39       165  176 0.9375000
40       163  174 0.9367816
41       162  163 0.9938650
42       161  185 0.8702703
43       155  164 0.9451220
44       150  180 0.8333333
45       148  169 0.8757396
46       146  171 0.8538012
47       145  166 0.8734940
48       144  162 0.8888889
49       139  183 0.7595628
50       139  161 0.8633540
51       136  148 0.9189189
52       133  140 0.9500000
53       133  144 0.9236111
54       131  150 0.8733333
55       129  148 0.8716216
56       126  132 0.9545455
57       124  145 0.8551724
58       122  151 0.8079470
59       115  129 0.8914729
60       113  160 0.7062500
61       112  126 0.8888889
62       112  137 0.8175182
63       112  141 0.7943262
64       112  130 0.8615385
65       108  115 0.9391304
66       108  127 0.8503937
67       107  118 0.9067797
68       104  118 0.8813559
69       100  111 0.9009009
70        96  113 0.8495575
71        94   98 0.9591837
72        94  105 0.8952381
73        94  106 0.8867925
74        87  105 0.8285714
75        85   96 0.8854167
76        85  111 0.7657658
77        85   98 0.8673469
78        85   91 0.9340659
79        81   96 0.8437500
80        81   91 0.8901099
81        78   84 0.9285714
82        77   98 0.7857143
83        77   87 0.8850575
84        77   85 0.9058824
85        76   88 0.8636364
86        74   80 0.9250000
87        74   81 0.9135802
88        74   94 0.7872340
89        74   86 0.8604651
90        73   86 0.8488372
91        73   88 0.8295455
92        73   80 0.9125000
93        73   78 0.9358974
94        72   83 0.8674699
95        71   91 0.7802198
96        69   72 0.9583333
97        69   77 0.8961039
98        69   79 0.8734177
99        69   71 0.9718310
100       68   72 0.9444444
101       68   76 0.8947368
102       67   76 0.8815789
103       66   74 0.8918919
104       65   70 0.9285714
105       64   77 0.8311688
106       64   69 0.9275362
107       63   67 0.9402985
108       61   66 0.9242424
109       60   64 0.9375000
110       60   72 0.8333333
111       60   66 0.9090909
112       60   68 0.8823529
113       59   65 0.9076923
114       59   63 0.9365079
115       59   65 0.9076923
116       56   58 0.9655172
117       56   66 0.8484848
118       55   60 0.9166667
119       54   62 0.8709677
120       54   63 0.8571429
121       54   58 0.9310345
122       54   66 0.8181818
123       53   59 0.8983051
124       53   67 0.7910448
125       53   55 0.9636364
126       53   65 0.8153846
127       52   59 0.8813559
128       52   61 0.8524590
129       52   54 0.9629630
130       52   55 0.9454545
131       51   61 0.8360656
132       51   57 0.8947368
133       50   55 0.9090909
134       50   56 0.8928571
135       49   54 0.9074074
136       49   51 0.9607843
137       48   56 0.8571429
138       48   50 0.9600000
139       48   63 0.7619048
140       48   50 0.9600000
141       48   61 0.7868852
142       47   54 0.8703704
143       47   48 0.9791667
144       46   50 0.9200000
145       46   48 0.9583333
146       46   56 0.8214286
147       46   50 0.9200000
148       46   54 0.8518519
149       44   60 0.7333333
150       43   57 0.7543860
151       43   47 0.9148936
152       43   45 0.9555556
153       43   46 0.9347826
154       42   46 0.9130435
155       42   59 0.7118644
156       41   43 0.9534884
157       40   48 0.8333333
158       39   50 0.7800000
159       39   42 0.9285714
160       38   47 0.8085106
161       38   46 0.8260870
162       38   42 0.9047619
163       37   42 0.8809524
164       37   44 0.8409091
165       37   46 0.8043478
166       37   41 0.9024390
167       36   42 0.8571429
168       36   37 0.9729730
169       36   44 0.8181818
170       35   40 0.8750000
171       34   41 0.8292683
172       34   37 0.9189189
173       33   35 0.9428571
174       33   37 0.8918919
175       32   35 0.9142857
176       32   35 0.9142857
177       32   35 0.9142857
178       32   42 0.7619048
179       32   34 0.9411765
180       32   38 0.8421053
181       31   33 0.9393939
182       31   31 1.0000000
183       30   31 0.9677419
184       30   37 0.8108108
185       30   33 0.9090909
186       30   33 0.9090909
187       30   35 0.8571429
188       29   34 0.8529412
189       29   33 0.8787879
190       29   41 0.7073171
191       28   30 0.9333333
192       28   37 0.7567568
193       28   43 0.6511628
194       28   35 0.8000000
195       28   32 0.8750000
196       28   35 0.8000000
197       27   32 0.8437500
198       27   33 0.8181818
199       27   30 0.9000000
200       27   29 0.9310345
201       27   28 0.9642857
202       27   29 0.9310345
203       27   29 0.9310345
204       27   30 0.9000000
205       26   32 0.8125000
206       26   31 0.8387097
207       26   38 0.6842105
208       26   26 1.0000000
209       26   42 0.6190476
210       26   32 0.8125000
211       26   35 0.7428571
212       26   32 0.8125000
213       25   27 0.9259259
214       25   25 1.0000000
215       25   34 0.7352941
216       25   25 1.0000000
217       25   28 0.8928571
218       25   28 0.8928571
219       24   30 0.8000000
220       24   25 0.9600000
221       24   31 0.7741935
222       23   25 0.9200000
223       23   24 0.9583333
224       23   23 1.0000000
225       23   28 0.8214286
226       23   23 1.0000000
227       23   23 1.0000000
228       23   27 0.8518519
229       23   26 0.8846154
230       22   30 0.7333333
231       22   24 0.9166667
232       22   39 0.5641026
233       22   24 0.9166667
234       22   23 0.9565217
235       22   26 0.8461538
236       22   26 0.8461538
237       22   38 0.5789474
238       22   26 0.8461538
239       22   25 0.8800000
240       21   24 0.8750000
241       21   27 0.7777778
242       21   22 0.9545455
243       21   21 1.0000000
244       21   21 1.0000000
245       21   23 0.9130435
246       21   26 0.8076923
247       21   21 1.0000000
248       20   20 1.0000000
249       20   25 0.8000000
250       20   21 0.9523810
251       20   20 1.0000000
252       20   21 0.9523810
253       20   21 0.9523810
254       20   22 0.9090909
255       20   21 0.9523810
256       19   20 0.9500000
257       19   21 0.9047619
258       19   20 0.9500000
259       19   21 0.9047619
260       19   22 0.8636364
261       19   26 0.7307692
262       19   21 0.9047619
263       19   21 0.9047619
264       19   19 1.0000000
265       19   20 0.9500000
266       19   20 0.9500000
267       19   21 0.9047619
268       19   20 0.9500000
269       18   19 0.9473684
270       18   19 0.9473684
271       18   20 0.9000000
272       18   19 0.9473684
273       18   23 0.7826087
274       18   20 0.9000000
275       18   20 0.9000000
276       18   22 0.8181818
277       18   20 0.9000000
278       18   20 0.9000000
279       18   23 0.7826087
280       18   19 0.9473684
281       18   20 0.9000000
282       17   17 1.0000000
283       17   22 0.7727273
284       17   24 0.7083333
285       17   17 1.0000000
286       17   18 0.9444444
287       17   18 0.9444444
288       17   18 0.9444444
289       17   17 1.0000000
290       17   21 0.8095238
291       17   17 1.0000000
292       17   17 1.0000000
293       17   18 0.9444444
294       17   18 0.9444444
295       16   17 0.9411765
296       16   16 1.0000000
297       16   25 0.6400000
298       16   16 1.0000000
299       16   17 0.9411765
300       16   18 0.8888889
301       16   17 0.9411765
302       16   17 0.9411765
303       16   19 0.8421053
304       16   16 1.0000000
305       16   17 0.9411765
306       16   17 0.9411765
307       16   18 0.8888889
308       16   16 1.0000000
309       16   20 0.8000000
310       15   15 1.0000000
311       15   16 0.9375000
312       15   16 0.9375000
313       15   16 0.9375000
314       15   16 0.9375000
315       15   19 0.7894737
316       15   16 0.9375000
317       15   16 0.9375000
318       15   17 0.8823529
319       15   16 0.9375000
320       15   19 0.7894737
321       15   16 0.9375000
322       15   18 0.8333333
323       15   15 1.0000000
324       15   20 0.7500000
325       15   15 1.0000000
326       15   15 1.0000000
327       15   18 0.8333333
328       15   20 0.7500000
329       14   14 1.0000000
330       14   22 0.6363636
331       14   15 0.9333333
332       14   14 1.0000000
333       14   16 0.8750000
334       14   18 0.7777778
335       14   19 0.7368421
336       14   16 0.8750000
337       14   16 0.8750000
338       14   14 1.0000000
339       14   16 0.8750000
340       14   15 0.9333333
341       14   15 0.9333333
342       14   15 0.9333333
343       14   16 0.8750000
344       14   14 1.0000000
345       14   16 0.8750000
346       14   16 0.8750000
347       14   20 0.7000000
348       14   14 1.0000000
349       14   17 0.8235294
350       14   15 0.9333333
351       14   15 0.9333333
352       14   15 0.9333333
353       14   17 0.8235294
354       13   17 0.7647059
355       13   16 0.8125000
356       13   15 0.8666667
357       13   13 1.0000000
358       13   13 1.0000000
359       13   15 0.8666667
360       13   15 0.8666667
361       13   14 0.9285714
362       13   13 1.0000000
363       13   13 1.0000000
364       13   15 0.8666667
365       13   15 0.8666667
366       13   17 0.7647059
367       13   13 1.0000000
368       13   17 0.7647059
369       13   14 0.9285714
370       13   15 0.8666667
371       13   17 0.7647059
372       12   12 1.0000000
373       12   12 1.0000000
374       12   13 0.9230769
375       12   15 0.8000000
376       12   12 1.0000000
377       12   14 0.8571429
378       12   12 1.0000000
379       12   17 0.7058824
380       12   13 0.9230769
381       12   12 1.0000000
382       12   13 0.9230769
383       12   12 1.0000000
384       12   16 0.7500000
385       12   12 1.0000000
386       12   13 0.9230769
387       12   12 1.0000000
388       12   16 0.7500000
389       12   12 1.0000000
390       12   12 1.0000000
391       12   13 0.9230769
392       12   12 1.0000000
393       12   12 1.0000000
394       11   17 0.6470588
395       11   11 1.0000000
396       11   12 0.9166667
397       11   11 1.0000000
398       11   12 0.9166667
399       11   14 0.7857143
400       11   11 1.0000000
401       11   12 0.9166667
402       11   11 1.0000000
403       11   12 0.9166667
404       11   15 0.7333333
405       11   13 0.8461538
406       11   11 1.0000000
407       11   13 0.8461538
408       11   11 1.0000000
409       11   11 1.0000000
410       11   11 1.0000000
411       11   11 1.0000000
412       11   12 0.9166667
413       11   13 0.8461538
414       11   11 1.0000000
415       10   11 0.9090909
416       10   11 0.9090909
417       10   15 0.6666667
418       10   11 0.9090909
419       10   10 1.0000000
420       10   11 0.9090909
421       10   12 0.8333333
422       10   10 1.0000000
423       10   11 0.9090909
424       10   11 0.9090909
425       10   14 0.7142857
426       10   12 0.8333333
427       10   11 0.9090909
428       10   11 0.9090909
429       10   12 0.8333333
430       10   11 0.9090909
431       10   11 0.9090909
432       10   10 1.0000000
433       10   12 0.8333333
434       10   11 0.9090909
435       10   10 1.0000000
436       10   10 1.0000000
437       10   10 1.0000000
438       10   10 1.0000000
439        9   10 0.9000000
440        9   11 0.8181818
441        9   13 0.6923077
442        9   11 0.8181818
443        9    9 1.0000000
444        9    9 1.0000000
445        9    9 1.0000000
446        9    9 1.0000000
447        9   10 0.9000000
448        9   10 0.9000000
449        9   10 0.9000000
450        9   10 0.9000000
451        9    9 1.0000000
452        9   11 0.8181818
453        9    9 1.0000000
454        9   12 0.7500000
455        9   10 0.9000000
456        9    9 1.0000000
457        9   11 0.8181818
458        9    9 1.0000000
459        9    9 1.0000000
460        9   11 0.8181818
461        9   10 0.9000000
462        9    9 1.0000000
463        9    9 1.0000000
464        9    9 1.0000000
465        9   13 0.6923077
466        8   12 0.6666667
467        8   13 0.6153846
468        8    9 0.8888889
469        8    8 1.0000000
470        8   11 0.7272727
471        8    9 0.8888889
472        8   14 0.5714286
473        8   10 0.8000000
474        8    9 0.8888889
475        8    9 0.8888889
476        8    9 0.8888889
477        8    8 1.0000000
478        8   10 0.8000000
479        8   10 0.8000000
480        8    9 0.8888889
481        8   13 0.6153846
482        8    8 1.0000000
483        8   11 0.7272727
484        8   11 0.7272727
485        8    9 0.8888889
486        8   10 0.8000000
487        8    8 1.0000000
488        8    9 0.8888889
489        8   12 0.6666667
490        8   11 0.7272727
491        7    8 0.8750000
492        7    9 0.7777778
493        7    7 1.0000000
494        7    7 1.0000000
495        7    8 0.8750000
496        7    8 0.8750000
497        7    8 0.8750000
498        7    9 0.7777778
499        7    7 1.0000000
500        7   11 0.6363636
501        7    7 1.0000000
502        7    7 1.0000000
503        7    8 0.8750000
504        7    9 0.7777778
505        7   11 0.6363636
506        7   10 0.7000000
507        7    7 1.0000000
508        7    7 1.0000000
509        7    8 0.8750000
510        7    8 0.8750000
511        7    7 1.0000000
512        7   10 0.7000000
513        7    7 1.0000000
514        7    7 1.0000000
515        7    8 0.8750000
516        7    8 0.8750000
517        7    9 0.7777778
518        7   13 0.5384615
519        7    7 1.0000000
520        7    7 1.0000000
521        7   10 0.7000000
522        6    6 1.0000000
523        6    7 0.8571429
524        6   10 0.6000000
525        6    6 1.0000000
526        6    7 0.8571429
527        6    7 0.8571429
528        6    6 1.0000000
529        6    7 0.8571429
530        6    6 1.0000000
531        6    8 0.7500000
532        6    8 0.7500000
533        6   12 0.5000000
534        6    6 1.0000000
535        6    6 1.0000000
536        6    8 0.7500000
537        6    6 1.0000000
538        6    6 1.0000000
539        6    6 1.0000000
540        6    6 1.0000000
541        6    8 0.7500000
542        6    7 0.8571429
543        6    7 0.8571429
544        6    7 0.8571429
545        6    7 0.8571429
546        6    6 1.0000000
547        6    8 0.7500000
548        6    6 1.0000000
549        6    7 0.8571429
550        6    7 0.8571429
551        6    6 1.0000000
552        6    6 1.0000000
553        6    7 0.8571429
554        6    7 0.8571429
555        6    6 1.0000000
556        6    6 1.0000000
557        6    6 1.0000000
558        6    6 1.0000000
559        6    8 0.7500000
560        6    6 1.0000000
561        6    6 1.0000000
562        6    6 1.0000000
563        6    6 1.0000000
564        6    6 1.0000000
565        6    6 1.0000000
566        5    5 1.0000000
567        5    5 1.0000000
568        5    5 1.0000000
569        5    6 0.8333333
570        5    5 1.0000000
571        5    5 1.0000000
572        5    5 1.0000000
573        5    6 0.8333333
574        5    5 1.0000000
575        5    5 1.0000000
576        5    5 1.0000000
577        5    5 1.0000000
578        5    6 0.8333333
579        5    5 1.0000000
580        5    6 0.8333333
581        5    5 1.0000000
582        5    5 1.0000000
583        5    5 1.0000000
584        5    8 0.6250000
585        5    6 0.8333333
586        5    5 1.0000000
587        5    5 1.0000000
588        5   10 0.5000000
589        5    5 1.0000000
590        5    6 0.8333333
591        5    5 1.0000000
592        5    5 1.0000000
593        5    5 1.0000000
594        5    5 1.0000000
595        5    5 1.0000000
596        5    5 1.0000000
597        5    5 1.0000000
598        5    5 1.0000000
599        5    5 1.0000000
600        5    5 1.0000000
601        5    6 0.8333333
602        5    5 1.0000000
603        5    8 0.6250000
604        5    5 1.0000000
605        5    5 1.0000000
606        5    5 1.0000000
607        5    5 1.0000000
608        4    4 1.0000000
609        4    4 1.0000000
610        4    5 0.8000000
611        4    4 1.0000000
612        4    4 1.0000000
613        4    5 0.8000000
614        4    4 1.0000000
615        4    4 1.0000000
616        4    4 1.0000000
617        4    4 1.0000000
618        4    4 1.0000000
619        4    6 0.6666667
620        4    4 1.0000000
621        4    4 1.0000000
622        4    4 1.0000000
623        4    4 1.0000000
624        4    5 0.8000000
625        4    4 1.0000000
626        4    4 1.0000000
627        4    4 1.0000000
628        4    8 0.5000000
629        4    4 1.0000000
630        4    5 0.8000000
631        4    4 1.0000000
632        4    5 0.8000000
633        4    4 1.0000000
634        4    4 1.0000000
635        4    4 1.0000000
636        4    6 0.6666667
637        4    4 1.0000000
638        4    7 0.5714286
639        4    4 1.0000000
640        4    5 0.8000000
641        4    6 0.6666667
642        4    4 1.0000000
643        4    4 1.0000000
644        4    5 0.8000000
645        4    4 1.0000000
646        4    4 1.0000000
647        4    4 1.0000000
648        4    4 1.0000000
649        4    4 1.0000000
650        4    4 1.0000000
651        4    4 1.0000000
652        4    6 0.6666667
653        3    3 1.0000000
654        3    3 1.0000000
655        3    3 1.0000000
656        3    3 1.0000000
657        3    3 1.0000000
658        3    4 0.7500000
659        3    3 1.0000000
660        3    3 1.0000000
661        3    3 1.0000000
662        3    5 0.6000000
663        3    6 0.5000000
664        3    3 1.0000000
665        3    3 1.0000000
666        3    3 1.0000000
667        3    3 1.0000000
668        3    3 1.0000000
669        3    3 1.0000000
670        3    3 1.0000000
671        3    4 0.7500000
672        3    4 0.7500000
673        3    4 0.7500000
674        3    3 1.0000000
675        3    3 1.0000000
676        3    3 1.0000000
677        3    3 1.0000000
678        3    3 1.0000000
679        3    4 0.7500000
680        3    3 1.0000000
681        3    3 1.0000000
682        3    3 1.0000000
683        3    3 1.0000000
684        3    3 1.0000000
685        3    3 1.0000000
686        3    3 1.0000000
687        3    3 1.0000000
688        3    3 1.0000000
689        3    3 1.0000000
690        3    4 0.7500000
691        3    4 0.7500000
692        3    3 1.0000000
693        3    4 0.7500000
694        3    3 1.0000000
695        3    3 1.0000000
696        3    3 1.0000000
697        3    3 1.0000000
698        3    4 0.7500000
699        3    3 1.0000000
700        3    3 1.0000000
701        3    3 1.0000000
702        3    3 1.0000000
703        3    3 1.0000000
704        3    3 1.0000000
705        3    3 1.0000000
706        3    3 1.0000000
707        3    3 1.0000000
708        3    3 1.0000000
709        3    7 0.4285714
710        3    4 0.7500000
711        3    3 1.0000000
712        3    3 1.0000000
713        2    2 1.0000000
714        2    2 1.0000000
715        2    2 1.0000000
716        2    4 0.5000000
717        2    2 1.0000000
718        2    2 1.0000000
719        2    2 1.0000000
720        2    2 1.0000000
721        2    2 1.0000000
722        2    2 1.0000000
723        2    2 1.0000000
724        2    2 1.0000000
725        2    3 0.6666667
726        2    2 1.0000000
727        2    2 1.0000000
728        2    2 1.0000000
729        2    2 1.0000000
730        2    2 1.0000000
731        2    7 0.2857143
732        2    2 1.0000000
733        2    3 0.6666667
734        2    2 1.0000000
735        2    2 1.0000000
736        2    4 0.5000000
737        2    2 1.0000000
738        2    3 0.6666667
739        2    2 1.0000000
740        2    2 1.0000000
741        2    2 1.0000000
742        2    2 1.0000000
743        2    2 1.0000000
744        2    2 1.0000000
745        2    2 1.0000000
746        2    2 1.0000000
747        2    2 1.0000000
748        2    3 0.6666667
749        2    2 1.0000000
750        2    2 1.0000000
751        2    2 1.0000000
752        2    2 1.0000000
753        2    2 1.0000000
754        2    2 1.0000000
755        2    2 1.0000000
756        2    2 1.0000000
757        2    5 0.4000000
758        2    3 0.6666667
759        2    2 1.0000000
760        2    3 0.6666667
761        2    2 1.0000000
762        2    2 1.0000000
763        2    2 1.0000000
764        2    2 1.0000000
765        2    2 1.0000000
766        2    2 1.0000000
767        2    2 1.0000000
768        2    5 0.4000000
769        2    2 1.0000000
770        2    2 1.0000000
771        2    2 1.0000000
772        2    2 1.0000000
773        2    2 1.0000000
774        2    3 0.6666667
775        2    2 1.0000000
776        2    2 1.0000000
777        2    2 1.0000000
778        2    3 0.6666667
779        2    4 0.5000000
780        2    2 1.0000000
781        2    2 1.0000000
782        2    3 0.6666667
783        2    2 1.0000000
784        2    2 1.0000000
785        2    6 0.3333333
786        2    2 1.0000000
787        2    2 1.0000000
788        2    2 1.0000000
789        2    2 1.0000000
790        2    2 1.0000000
791        2    3 0.6666667
792        2    2 1.0000000
793        2    8 0.2500000
794        2    2 1.0000000
795        2    2 1.0000000
796        2    2 1.0000000
797        2    2 1.0000000
798        2    3 0.6666667
799        2    2 1.0000000
800        2    2 1.0000000
801        2    2 1.0000000
802        2    2 1.0000000
803        2    2 1.0000000
804        2    2 1.0000000
805        2    2 1.0000000
806        2    2 1.0000000
807        2    3 0.6666667
808        2    3 0.6666667
809        2    2 1.0000000
810        2    5 0.4000000
811        2    4 0.5000000
812        2    2 1.0000000
813        2    2 1.0000000
814        2    2 1.0000000
815        2    2 1.0000000
816        2    2 1.0000000
817        2    3 0.6666667
818        2    2 1.0000000
819        1    1 1.0000000
820        1    1 1.0000000
821        1    1 1.0000000
822        1    1 1.0000000
823        1    1 1.0000000
824        1    1 1.0000000
825        1    1 1.0000000
826        1    1 1.0000000
827        1    2 0.5000000
828        1    1 1.0000000
829        1    1 1.0000000
830        1    1 1.0000000
831        1    1 1.0000000
832        1    1 1.0000000
833        1    1 1.0000000
834        1    2 0.5000000
835        1    1 1.0000000
836        1    1 1.0000000
837        1    1 1.0000000
838        1    1 1.0000000
839        1    1 1.0000000
840        1    2 0.5000000
841        1    1 1.0000000
842        1    2 0.5000000
843        1    1 1.0000000
844        1    2 0.5000000
845        1    1 1.0000000
846        1    1 1.0000000
847        1    1 1.0000000
848        1    1 1.0000000
849        1    1 1.0000000
850        1    1 1.0000000
851        1    1 1.0000000
852        1    1 1.0000000
853        1    1 1.0000000
854        1    1 1.0000000
855        1    1 1.0000000
856        1    1 1.0000000
857        1    1 1.0000000
858        1    1 1.0000000
859        1    2 0.5000000
860        1    2 0.5000000
861        1    1 1.0000000
862        1    1 1.0000000
863        1    1 1.0000000
864        1    1 1.0000000
865        1    1 1.0000000
866        1    1 1.0000000
867        1    1 1.0000000
868        1    1 1.0000000
869        1    1 1.0000000
870        1    1 1.0000000
871        1    1 1.0000000
872        1    1 1.0000000
873        1    1 1.0000000
874        1    1 1.0000000
875        1    1 1.0000000
876        1    1 1.0000000
877        1    1 1.0000000
878        1    2 0.5000000
879        1    1 1.0000000
880        1    1 1.0000000
881        1    1 1.0000000
882        1    1 1.0000000
883        1    1 1.0000000
884        1    1 1.0000000
885        1    1 1.0000000
886        1    1 1.0000000
887        1    1 1.0000000
888        1    1 1.0000000
889        1    1 1.0000000
890        1    1 1.0000000
891        1    1 1.0000000
892        1    1 1.0000000
893        1    1 1.0000000
894        1    1 1.0000000
895        1    1 1.0000000
896        1    1 1.0000000
897        1    1 1.0000000
898        1    1 1.0000000
899        1    1 1.0000000
900        1    1 1.0000000
901        1    1 1.0000000
902        1    1 1.0000000
903        1    2 0.5000000
904        1    1 1.0000000
905        1    1 1.0000000
906        1    1 1.0000000
907        1    1 1.0000000
908        1    1 1.0000000
909        1    1 1.0000000
910        1    1 1.0000000
911        1    1 1.0000000
912        1    1 1.0000000
913        1    1 1.0000000
914        1    1 1.0000000
915        1    1 1.0000000
916        1    1 1.0000000
917        1    2 0.5000000
918        1    1 1.0000000
919        1    1 1.0000000
920        1    1 1.0000000
921        1    1 1.0000000
922        1    1 1.0000000
923        1    1 1.0000000
924        1    1 1.0000000
925        1    1 1.0000000
926        1    1 1.0000000
927        1    1 1.0000000
928        1    2 0.5000000
929        1    1 1.0000000
930        1    1 1.0000000
931        1    1 1.0000000
932        1    1 1.0000000
933        1    1 1.0000000
934        1    1 1.0000000
935        1    1 1.0000000
936        1    2 0.5000000
937        1    1 1.0000000
938        1    1 1.0000000
939        1    2 0.5000000
940        1    1 1.0000000
941        1    1 1.0000000
942        1    1 1.0000000
943        1    1 1.0000000
944        1    1 1.0000000
945        1    2 0.5000000
946        1    1 1.0000000
947        1    1 1.0000000
948        1    1 1.0000000
949        1    1 1.0000000
950        1    1 1.0000000
951        1    1 1.0000000
952        1    1 1.0000000
953        1    2 0.5000000
954        1    1 1.0000000
955        1    1 1.0000000
956        1    1 1.0000000
957        1    1 1.0000000
958        1    1 1.0000000
959        1    1 1.0000000
960        1    1 1.0000000
961        1    1 1.0000000
962        1    1 1.0000000
963        1    1 1.0000000
964        1    2 0.5000000
965        1    1 1.0000000
966        1    1 1.0000000
967        1    1 1.0000000
968        1    1 1.0000000
969        1    1 1.0000000
970        1    1 1.0000000
971        1    1 1.0000000
972        1    1 1.0000000
973        1    1 1.0000000
974        1    1 1.0000000
975        1    1 1.0000000
976        1    1 1.0000000
977        1    1 1.0000000
978        1    1 1.0000000
979        1    1 1.0000000
980        1    2 0.5000000
981        1    1 1.0000000
982        0    1 0.0000000
983        0    2 0.0000000
984        0    1 0.0000000
985        0    3 0.0000000
986        0    2 0.0000000
987        0    1 0.0000000
988        0    7 0.0000000
989        0    1 0.0000000
990        0    1 0.0000000
991        0    1 0.0000000
992        0    6 0.0000000
993        0    1 0.0000000
994        0    1 0.0000000
995        0    1 0.0000000
996        0    1 0.0000000
997        0    1 0.0000000
998        0    1 0.0000000
999        0    2 0.0000000
1000       0    1 0.0000000
1001       0    1 0.0000000</code></pre>
</div>
</div>
<p>We would like to keep those traits with large number of shared genes with HTN related traits, at the same time, the proption of those shared genes is also high among trait specic hits. In anothe words, the large number of shared genes are not driven by its own large number of GWAS hits.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(oth.sameGene<span class="sc">$</span>Freq, oth.sameGene<span class="sc">$</span>sameGCt, <span class="at">xlim=</span><span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1400</span>), <span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1400</span>), <span class="at">xlab=</span><span class="st">"Total SNPs reported"</span>, <span class="at">ylab=</span><span class="st">"Shared gene counts with HTN"</span>, <span class="at">main=</span><span class="fu">c</span>(<span class="st">"By Traits: Number of GWAS hits"</span>, <span class="st">"vs. Number of Shared Genes"</span>))</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">a=</span><span class="dv">0</span>, <span class="at">b=</span><span class="dv">1</span>,<span class="at">lty=</span><span class="st">"dotted"</span>, <span class="at">col=</span><span class="st">"blue"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="doc_pheGenoI_network_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Only keep the traits with total SNPs reported &gt; 800. We considered “Body Mass Index”, “Bronchodilator Agents”, and “Cholesterol, HDL” most related to HTN related traits due to enrichment of shared genes among them.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>trait.related <span class="ot">=</span> oth.sameGene <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Freq<span class="sc">&gt;</span><span class="dv">800</span>)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>trait.related</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  Trait sameGCt Freq      prop
1       Body Mass Index    1061 1135 0.9348018
2 Bronchodilator Agents    1048 1134 0.9241623
3      Cholesterol, HDL     801  904 0.8860619</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>dd.othKept <span class="ot">=</span> dd.oth <span class="sc">%&gt;%</span> <span class="fu">filter</span>( <span class="fu">is.element</span>(Trait, trait.related<span class="sc">$</span>Trait))</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(dd.othKept)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3173   18</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>dd.trait2 <span class="ot">=</span> <span class="fu">rbind</span>(dd.othKept, dd.trait1)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>da.ven <span class="ot">=</span> dd.trait2 <span class="sc">%&gt;%</span> <span class="fu">select</span>(Trait, Gene) <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(Trait) <span class="sc">%&gt;%</span> <span class="fu">summarise_all</span>(<span class="sc">~</span><span class="fu">list</span>(<span class="fu">unique</span>(Gene)))</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(da.ven)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [5 × 2] (S3: tbl_df/tbl/data.frame)
 $ Trait: chr [1:5] "Blood Pressure" "Body Mass Index" "Bronchodilator Agents" "Cholesterol, HDL" ...
 $ Gene :List of 5
  ..$ : chr [1:2055] "TAS1R3" "MORN1" "LOC100129534" "PANK4" ...
  ..$ : chr [1:423] "LINC01134" "KAZN" "LINC01141" "PTPRU" ...
  ..$ : chr [1:218] "PRDM16" "CAMTA1" "TXNP2" "VAV3-AS1" ...
  ..$ : chr [1:347] "RPL7AP18" "KAZN" "PTPRU" "PDE4B" ...
  ..$ : chr [1:219] "PRDM16" "CASZ1" "MTHFR" "KDM4A" ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>da.ven.plot.input <span class="ot">=</span> da.ven<span class="sc">$</span>Gene</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(da.ven.plot.input)<span class="ot">=</span>da.ven<span class="sc">$</span>Trait</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(da.ven.plot.input)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>List of 5
 $ Blood Pressure       : chr [1:2055] "TAS1R3" "MORN1" "LOC100129534" "PANK4" ...
 $ Body Mass Index      : chr [1:423] "LINC01134" "KAZN" "LINC01141" "PTPRU" ...
 $ Bronchodilator Agents: chr [1:218] "PRDM16" "CAMTA1" "TXNP2" "VAV3-AS1" ...
 $ Cholesterol, HDL     : chr [1:347] "RPL7AP18" "KAZN" "PTPRU" "PDE4B" ...
 $ Hypertension         : chr [1:219] "PRDM16" "CASZ1" "MTHFR" "KDM4A" ...</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="do">## double checking code</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>da.ven2 <span class="ot">=</span> dd.trait2 <span class="sc">%&gt;%</span> <span class="fu">select</span>(Trait, Gene)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>tmp <span class="ot">=</span> <span class="fu">tapply</span>(da.ven2, <span class="fu">list</span>(da.ven2<span class="sc">$</span>Trait), unique)</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(tmp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>List of 5
 $ Blood Pressure       :'data.frame':  2055 obs. of  2 variables:
  ..$ Trait: chr [1:2055] "Blood Pressure" "Blood Pressure" "Blood Pressure" "Blood Pressure" ...
  ..$ Gene : chr [1:2055] "TAS1R3" "MORN1" "LOC100129534" "PANK4" ...
 $ Body Mass Index      :'data.frame':  423 obs. of  2 variables:
  ..$ Trait: chr [1:423] "Body Mass Index" "Body Mass Index" "Body Mass Index" "Body Mass Index" ...
  ..$ Gene : chr [1:423] "LINC01134" "KAZN" "LINC01141" "PTPRU" ...
 $ Bronchodilator Agents:'data.frame':  218 obs. of  2 variables:
  ..$ Trait: chr [1:218] "Bronchodilator Agents" "Bronchodilator Agents" "Bronchodilator Agents" "Bronchodilator Agents" ...
  ..$ Gene : chr [1:218] "PRDM16" "CAMTA1" "TXNP2" "VAV3-AS1" ...
 $ Cholesterol, HDL     :'data.frame':  347 obs. of  2 variables:
  ..$ Trait: chr [1:347] "Cholesterol, HDL" "Cholesterol, HDL" "Cholesterol, HDL" "Cholesterol, HDL" ...
  ..$ Gene : chr [1:347] "RPL7AP18" "KAZN" "PTPRU" "PDE4B" ...
 $ Hypertension         :'data.frame':  219 obs. of  2 variables:
  ..$ Trait: chr [1:219] "Hypertension" "Hypertension" "Hypertension" "Hypertension" ...
  ..$ Gene : chr [1:219] "PRDM16" "CASZ1" "MTHFR" "KDM4A" ...
 - attr(*, "dim")= int 5
 - attr(*, "dimnames")=List of 1
  ..$ : chr [1:5] "Blood Pressure" "Body Mass Index" "Bronchodilator Agents" "Cholesterol, HDL" ...</code></pre>
</div>
</div>
</section>
</section>
<section id="venn-diagrams-showing-shared-genes" class="level2">
<h2 class="anchored" data-anchor-id="venn-diagrams-showing-shared-genes">Venn diagrams showing shared genes</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"ggVennDiagram"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'ggVennDiagram'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:tidyr':

    unite</code></pre>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggVennDiagram</span>(da.ven.plot.input, <span class="at">label_alpha =</span> <span class="dv">0</span>, <span class="at">label=</span><span class="st">"count"</span>)<span class="sc">+</span> </span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_gradient</span>(<span class="at">low =</span> <span class="st">"#F4FAFE"</span>, <span class="at">high =</span> <span class="st">"#4981BF"</span>)<span class="sc">+</span><span class="fu">scale_x_continuous</span>(<span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> .<span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="doc_pheGenoI_network_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggVennDiagram</span>(da.ven.plot.input[<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">5</span>)], <span class="at">label_alpha =</span> <span class="dv">0</span>)<span class="sc">+</span><span class="fu">scale_fill_distiller</span>(<span class="at">palette =</span> <span class="st">"RdBu"</span>)<span class="sc">+</span><span class="fu">scale_x_continuous</span>(<span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> .<span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="doc_pheGenoI_network_files/figure-html/unnamed-chunk-15-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggVennDiagram</span>(da.ven.plot.input[<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">4</span>,<span class="dv">5</span>)], <span class="at">label_alpha =</span> <span class="dv">0</span>)<span class="sc">+</span><span class="fu">scale_fill_distiller</span>(<span class="at">palette =</span> <span class="st">"RdBu"</span>)<span class="sc">+</span><span class="fu">scale_x_continuous</span>(<span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> .<span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="doc_pheGenoI_network_files/figure-html/unnamed-chunk-15-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggVennDiagram</span>(da.ven.plot.input[<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">5</span>)], <span class="at">label_alpha =</span> <span class="dv">0</span>)<span class="sc">+</span><span class="fu">scale_fill_distiller</span>(<span class="at">palette =</span> <span class="st">"RdBu"</span>)<span class="sc">+</span><span class="fu">scale_x_continuous</span>(<span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> .<span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="doc_pheGenoI_network_files/figure-html/unnamed-chunk-15-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggVennDiagram</span>(da.ven.plot.input[<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>,<span class="dv">5</span>)], <span class="at">label_alpha =</span> <span class="dv">0</span>)<span class="sc">+</span><span class="fu">scale_fill_distiller</span>(<span class="at">palette =</span> <span class="st">"RdBu"</span>)<span class="sc">+</span><span class="fu">scale_x_continuous</span>(<span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> .<span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="doc_pheGenoI_network_files/figure-html/unnamed-chunk-15-5.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggVennDiagram</span>(da.ven.plot.input[<span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>)], <span class="at">label_alpha =</span> <span class="dv">0</span>)<span class="sc">+</span><span class="fu">scale_fill_distiller</span>(<span class="at">palette =</span> <span class="st">"RdBu"</span>)<span class="sc">+</span><span class="fu">scale_x_continuous</span>(<span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> .<span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="doc_pheGenoI_network_files/figure-html/unnamed-chunk-15-6.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="gene-network-overlaid-by-protein-network" class="level2">
<h2 class="anchored" data-anchor-id="gene-network-overlaid-by-protein-network">Gene network overlaid by protein network</h2>
<p>We extracted the genes shared among hypertension, blood pressure and cholesterol (HDL), and construct the network showing the strength of association signals. We also query the protein network predicted by STRING.db using the whole list of genes associated with the three traits.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>dd.network <span class="ot">=</span> dd.trait2 <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">is.element</span>(Trait, da.ven<span class="sc">$</span>Trait[<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">4</span>,<span class="dv">5</span>)])) <span class="sc">%&gt;%</span> <span class="fu">select</span>(Trait, Gene, Chromosome, p.sig, Context)</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(dd.network)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5880    5</code></pre>
</div>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">write.table</span>(dd.network, <span class="at">file=</span><span class="st">"network_HTN_3T_GWAS_gene.csv"</span>, <span class="at">sep=</span><span class="st">","</span>, <span class="at">quote=</span>T, <span class="at">col.names =</span> T, <span class="at">row.names =</span> F)                                  </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>